mod attachments;
mod bulk_update;
mod config;
mod conflicts;
mod context;
mod data_safety;
mod demo;
mod demo_data;
mod doctor;
mod labels;
mod metadata;
mod notes;
mod prime;
mod projects;
mod recurrence;
mod relations;
mod self_update;
mod skill;
mod tasks;
mod text;
mod validation;
mod workspaces;

pub(crate) use self::attachments::cmd_attachment;
pub(crate) use self::bulk_update::cmd_bulk_update;
pub(crate) use self::config::cmd_config;
pub(crate) use self::conflicts::cmd_conflict;
pub(crate) use self::context::cmd_context;
pub(crate) use self::data_safety::{cmd_backup, cmd_backup_restore, cmd_export, cmd_import};
pub(crate) use self::demo::{cmd_demo, cmd_internal_demo_snapshot};
pub(crate) use self::doctor::cmd_doctor;
pub(crate) use self::labels::cmd_label;
pub(crate) use self::metadata::cmd_metadata;
pub(crate) use self::notes::{cmd_note, cmd_note_delete};
pub(crate) use self::prime::run as cmd_prime;
pub(crate) use self::projects::cmd_project;
pub(crate) use self::recurrence::{cmd_recur, recurrence_schedule};
pub(crate) use self::relations::{cmd_dep, cmd_epic, cmd_related};
pub(crate) use self::self_update::run as cmd_self_update;
pub(crate) use self::skill::{install as cmd_skill_install, print as cmd_skill};
pub(crate) use self::tasks::{
    cmd_add, cmd_delete_restore, cmd_edit, cmd_internal_natural_add, cmd_list, cmd_search, cmd_show,
};
pub(crate) use self::text::cmd_text;
pub(crate) use self::workspaces::cmd_workspace;
